export const EDIT_AUTH: Lowercase<string> = 'edit_auth'
export const EDIT_USER_UID: Lowercase<string> = 'edit_user_uid'
export const EDIT_USER_NAME: Lowercase<string> = 'edit_user_name'
export const EDIT_USER_DATE_OF_REGISTRATON: Lowercase<string> = 'edit_user_date_of_registration'
export const ADD_USER_POST: Lowercase<string> = 'add_user_post'
export const DELETE_USER_POST: Lowercase<string> = 'delete_user_post'
export const EDIT_NEWS_REACTION: Lowercase<string> = 'edit_news_reaction'
export const EDIT_NEWS_REACTION_VIEWS: Lowercase<string> = 'edit_news_reaction_views'
export const ADD_USER_REACTION: Lowercase<string> = 'add_user_reaction'
export const EDIT_USER_REACTION: Lowercase<string> = 'edit_user_reaction'
export const EDIT_NEWS_LIKES_AND_DISLIKES: Lowercase<string> = 'edit_news_likes_and_dislikes'
export const DELETE_USER_REACTION: Lowercase<string> = 'delete_user_reaction'
export const EDIT_NEWS: Lowercase<string> = 'add_news'

export const ADD_NEWS_ONE: Lowercase<string> = 'add_news_one'
export const EDIT_NEWS_ONE: Lowercase<string> = 'edit_news_one'
export const DELETE_NEWS_ONE: Lowercase<string> = 'delete_news_one'

export const ADD_NEWS_POST_COMMENT: Lowercase<string> = 'add_news_post_comment'
export const DELETE_NEWS_POST_COMMENT: Lowercase<string> = 'delete_news_post_comment'

export const ADD_NEWS_POST_COMMENT_REACTION: Lowercase<string> = 'add_news_post_comment_reaction'
export const EDIT_NEWS_POST_COMMENT_REACTION: Lowercase<string> = 'edit_news_post_comment_reaction'
export const DELETE_NEWS_POST_COMMENT_REACTION: Lowercase<string> = 'delete_news_post_comment_reaction'
export const EDIT_NEWS_POST_COMMENT_REACTION_LIKES_AND_DISLIKES: Lowercase<string> = 'edit_news_post_comment_reaction_likes_and_dislikes'

export const EDIT_NEWS_LOADING: Lowercase<string> = 'edit_news_loading'