export const EDIT_AUTH: Lowercase<string> = 'edit_auth'
export const EDIT_USER_UID: Lowercase<string> = 'edit_user_uid'
export const EDIT_USER_NAME: Lowercase<string> = 'edit_user_name'
export const EDIT_DATE_OF_REGISTRATON: Lowercase<string> = 'edit_date_of_registration'
export const ADD_POST: Lowercase<string> = 'add_post'
export const DELETE_POST: Lowercase<string> = 'delete_post'